steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/PRJOECT_ID/IMAGE_NAME', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/PRJOECT_ID/IMAGE_NAME']
images: ['gcr.io/PRJOECT_ID/IMAGE_NAME']
options:
  logging: CLOUD_LOGGING_ONLY
